version: "3.8"
services:
  api:
    build: ./backend
    container_name: fb-back-cont
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    container_name: fb-front-cont
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
